import time from './time-manager.png';
import calculator from './calculator2.png';
import drumMachine from './drumMachine.png';
import markDown from './markDown.png';
import randomQuote from './randomQuote.png';
import illustrator from './illustrator.svg';
import jquery from './jquery.svg';
import redux from './redux.svg';
import photoshop from './photoshop.svg';

export { time };
export { calculator };
export { drumMachine };
export { markDown };
export { randomQuote };
export { illustrator };
export { jquery };
export { redux };
export { photoshop };